https://chatgpt.com/share/66e39c33-817c-800c-8fd9-5eaa66eb888e

In [1]:
#question 1
import pandas as pd
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv"
df = pd.read_csv(url)
df.isna().sum()

row_n           0
id              1
name            0
gender          0
species         0
birthday        0
personality     0
song           11
phrase          0
full_id         0
url             0
dtype: int64

In [2]:
#question 2
import pandas as pd

# Load the dataset from the URL
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv"
df = pd.read_csv(url)

# Get the number of rows and columns
rows, columns = df.shape

# Print the results
print(f'The dataset contains {rows} rows and {columns} columns.')

The dataset contains 391 rows and 11 columns.

question 2.2
variables that are objects that are being observed. For example, for my dataset on question 1, it would be id, name, gender, species, birthday. Variable contains the information about the dataset and dataset is a group of variables and its corresponding values. In other words it is the data type that we are gathering. Where observation is the data itself of an entity or an object. In my dataset, observation is the data of all variables for a villager.

In [3]:
import pandas as pd

# Load the dataset from the URL
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv"
df = pd.read_csv(url)

# Step 1: Numeric Summary
print("Numeric Summary:")
print(df.describe())  # Summary statistics for numeric columns
print()

# Step 2: Unique Values and Frequency Counts for categorical columns
print("Categorical Column Summaries:")
categorical_columns = df.select_dtypes(include=['object']).columns
for column in categorical_columns:
    print(f"\nValue counts for '{column}':")
    print(df[column].value_counts())
print()

# Step 3: Missing Values
print("Missing Values by Column:")
print(df.isna().sum())  # Check for missing values
print()

# Step 4: Data Types of Each Column
print("Data Types of Columns:")
print(df.dtypes)

Numeric Summary:
            row_n
count  391.000000
mean   239.902813
std    140.702672
min      2.000000
25%    117.500000
50%    240.000000
75%    363.500000
max    483.000000

Categorical Column Summaries:

Value counts for 'id':
id
admiral    1
mott       1
paula      1
patty      1
pate       1
          ..
eloise     1
elmer      1
ellie      1
elise      1
zucker     1
Name: count, Length: 390, dtype: int64

Value counts for 'name':
name
Admiral    1
Muffy      1
Paula      1
Patty      1
Pate       1
          ..
Elvis      1
Eloise     1
Elmer      1
Ellie      1
Zucker     1
Name: count, Length: 391, dtype: int64

Value counts for 'gender':
gender
male      204
female    187
Name: count, dtype: int64

Value counts for 'species':
species
cat          23
rabbit       20
frog         18
squirrel     18
duck         17
dog          16
cub          16
pig          15
bear         15
mouse        15
horse        15
bird         13
penguin      13
sheep        13
elephant     11
wolf         11
ostrich      10
deer         10
eagle         9
gorilla       9
chicken       9
koala         9
goat          8
hamster       8
kangaroo      8
monkey        8
anteater      7
hippo         7
tiger         7
alligator     7
lion          7
bull          6
rhino         6
cow           4
octopus       3
Name: count, dtype: int64

Value counts for 'birthday':
birthday
1-27     2
12-5     2
7-31     2
3-26     2
8-3      2
        ..
4-3      1
10-26    1
7-23     1
12-8     1
3-8      1
Name: count, Length: 361, dtype: int64

Value counts for 'personality':
personality
lazy      60
normal    59
cranky    55
snooty    55
jock      55
peppy     49
smug      34
uchi      24
Name: count, dtype: int64

Value counts for 'song':
song
K.K. Country     10
Forest Life       9
Imperial K.K.     7
K.K. Soul         7
K.K. Ragtime      7
                 ..
Aloha K.K.        2
Drivin'           1
Senor K.K.        1
K.K.  Bazaar      1
K.K. D&B          1
Name: count, Length: 92, dtype: int64

Value counts for 'phrase':
phrase
wee one       2
quacko        2
bloop         2
aye aye       1
snoot         1
             ..
lambchop      1
yeah buddy    1
chow down     1
unh-hunh      1
pronk         1
Name: count, Length: 388, dtype: int64

Value counts for 'full_id':
full_id
villager-admiral    1
villager-muffy      1
villager-paula      1
villager-patty      1
villager-pate       1
                   ..
villager-elvis      1
villager-eloise     1
villager-elmer      1
villager-ellie      1
villager-zucker     1
Name: count, Length: 391, dtype: int64

Value counts for 'url':
url
https://villagerdb.com/images/villagers/thumb/admiral.98206ee.png    1
https://villagerdb.com/images/villagers/thumb/muffy.1497c92.png      1
https://villagerdb.com/images/villagers/thumb/paula.563ba81.png      1
https://villagerdb.com/images/villagers/thumb/patty.3e17f7f.png      1
https://villagerdb.com/images/villagers/thumb/pate.c60838c.png       1
                                                                    ..
https://villagerdb.com/images/villagers/thumb/elvis.57d4757.png      1
https://villagerdb.com/images/villagers/thumb/eloise.112208b.png     1
https://villagerdb.com/images/villagers/thumb/elmer.cc7df52.png      1
https://villagerdb.com/images/villagers/thumb/ellie.5a144a6.png      1
https://villagerdb.com/images/villagers/thumb/zucker.8dbb719.png     1
Name: count, Length: 391, dtype: int64

Missing Values by Column:
row_n           0
id              1
name            0
gender          0
species         0
birthday        0
personality     0
song           11
phrase          0
full_id         0
url             0
dtype: int64

Data Types of Columns:
row_n           int64
id             object
name           object
gender         object
species        object
birthday       object
personality    object
song           object
phrase         object
full_id        object
url            object
dtype: object

In [5]:
import pandas as pd

# Load the dataset from the URL
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv"
df = pd.read_csv(url)

# 1. Summary of Numeric Data
print("### Numeric Summary ###")
print(df.describe())
print("\n")  # Adds a newline for better separation

# 2. Summary of Categorical Data
print("### Categorical Column Summaries ###")
categorical_columns = df.select_dtypes(include=['object']).columns
for column in categorical_columns:
    print(f"\nFrequency of values in '{column}':")
    print(df[column].value_counts())
print("\n")  # Adds a newline for better separation

# 3. Checking for Missing Data
print("### Missing Values by Column ###")
print(df.isna().sum())
print("\n")  # Adds a newline for better separation

# 4. Understanding Data Types
print("### Data Types of Columns ###")
print(df.dtypes)

### Numeric Summary ###
            row_n
count  391.000000
mean   239.902813
std    140.702672
min      2.000000
25%    117.500000
50%    240.000000
75%    363.500000
max    483.000000


### Categorical Column Summaries ###

Frequency of values in 'id':
id
admiral    1
mott       1
paula      1
patty      1
pate       1
          ..
eloise     1
elmer      1
ellie      1
elise      1
zucker     1
Name: count, Length: 390, dtype: int64

Frequency of values in 'name':
name
Admiral    1
Muffy      1
Paula      1
Patty      1
Pate       1
          ..
Elvis      1
Eloise     1
Elmer      1
Ellie      1
Zucker     1
Name: count, Length: 391, dtype: int64

Frequency of values in 'gender':
gender
male      204
female    187
Name: count, dtype: int64

Frequency of values in 'species':
species
cat          23
rabbit       20
frog         18
squirrel     18
duck         17
dog          16
cub          16
pig          15
bear         15
mouse        15
horse        15
bird         13
penguin      13
sheep        13
elephant     11
wolf         11
ostrich      10
deer         10
eagle         9
gorilla       9
chicken       9
koala         9
goat          8
hamster       8
kangaroo      8
monkey        8
anteater      7
hippo         7
tiger         7
alligator     7
lion          7
bull          6
rhino         6
cow           4
octopus       3
Name: count, dtype: int64

Frequency of values in 'birthday':
birthday
1-27     2
12-5     2
7-31     2
3-26     2
8-3      2
        ..
4-3      1
10-26    1
7-23     1
12-8     1
3-8      1
Name: count, Length: 361, dtype: int64

Frequency of values in 'personality':
personality
lazy      60
normal    59
cranky    55
snooty    55
jock      55
peppy     49
smug      34
uchi      24
Name: count, dtype: int64

Frequency of values in 'song':
song
K.K. Country     10
Forest Life       9
Imperial K.K.     7
K.K. Soul         7
K.K. Ragtime      7
                 ..
Aloha K.K.        2
Drivin'           1
Senor K.K.        1
K.K.  Bazaar      1
K.K. D&B          1
Name: count, Length: 92, dtype: int64

Frequency of values in 'phrase':
phrase
wee one       2
quacko        2
bloop         2
aye aye       1
snoot         1
             ..
lambchop      1
yeah buddy    1
chow down     1
unh-hunh      1
pronk         1
Name: count, Length: 388, dtype: int64

Frequency of values in 'full_id':
full_id
villager-admiral    1
villager-muffy      1
villager-paula      1
villager-patty      1
villager-pate       1
                   ..
villager-elvis      1
villager-eloise     1
villager-elmer      1
villager-ellie      1
villager-zucker     1
Name: count, Length: 391, dtype: int64

Frequency of values in 'url':
url
https://villagerdb.com/images/villagers/thumb/admiral.98206ee.png    1
https://villagerdb.com/images/villagers/thumb/muffy.1497c92.png      1
https://villagerdb.com/images/villagers/thumb/paula.563ba81.png      1
https://villagerdb.com/images/villagers/thumb/patty.3e17f7f.png      1
https://villagerdb.com/images/villagers/thumb/pate.c60838c.png       1
                                                                    ..
https://villagerdb.com/images/villagers/thumb/elvis.57d4757.png      1
https://villagerdb.com/images/villagers/thumb/eloise.112208b.png     1
https://villagerdb.com/images/villagers/thumb/elmer.cc7df52.png      1
https://villagerdb.com/images/villagers/thumb/ellie.5a144a6.png      1
https://villagerdb.com/images/villagers/thumb/zucker.8dbb719.png     1
Name: count, Length: 391, dtype: int64


### Missing Values by Column ###
row_n           0
id              1
name            0
gender          0
species         0
birthday        0
personality     0
song           11
phrase          0
full_id         0
url             0
dtype: int64


### Data Types of Columns ###
row_n           int64
id             object
name           object
gender         object
species        object
birthday       object
personality    object
song           object
phrase         object
full_id        object
url            object
dtype: object

In [14]:
#question 4
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
td = pd.read_csv(url)
td.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [13]:
#question 4
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
td = pd.read_csv(url)
td.isna().sum()

td.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

question 4
td.shape() gives the how many rows and columns the data set is. For example, it would likely give the number of observations and variables in the dataset. This means that it will count for missing data as well. On the other hand, td.discribe() will not account for missing values. It would also not account for non-numeric vales such as sex, embarked, and embark_town. Count shown in td.describe does not count the numbers of observations that are non-numeric or missing.

In [17]:
import pandas as pd

# Example DataFrame
data = {
    'department': ['HR', 'IT', 'IT', 'HR', 'Finance', 'HR', 'Finance', 'IT'],
    'salary': [50000, 60000, 65000, 55000, 70000, 53000, 72000, 62000]
}
df = pd.DataFrame(data)

# Group by 'department' and describe 'salary'
result = df.groupby('department')['salary'].describe()
print(result)
grouped = df.groupby("department")
grouped.describe()

            count          mean          std      min      25%      50%  \
department
Finance       2.0  71000.000000  1414.213562  70000.0  70500.0  71000.0
HR            3.0  52666.666667  2516.611478  50000.0  51500.0  53000.0
IT            3.0  62333.333333  2516.611478  60000.0  61000.0  62000.0

                75%      max
department
Finance     71500.0  72000.0
HR          54000.0  55000.0
IT          63500.0  65000.0
<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7fcbf2ab5a50>

question 8
1.
groupby("catagory") gives a dataset of the observation "catagory". For example 

data = {
    'favorite_subjects': ['Math', 'Math', 'Stats', 'Physics'],
    'students': ['Joe', 'Daniel', 'Samuel', 'Jason'],
    'grades': ['80', '100','78','50']
}
df = pd.DataFrame(data)


df.groupby("favorite_subjects")
would give

Data set of Math with (Joe and Daniel) and (A, A)
Stats with Samuel and A
Physics with Jason and B

where if we specify it as
groupby("favorite_subjects")['students'],

it would be 
Data set of Math with Joe and Daniel
Stats with Samuel
Physics with Jason

2.
count in df.describe() shows the number of observations in a variable of the dataset not counting missing data.

count in df.groupby("col1")["col2"].describe() shows the number of observations in col2 that falls under col1. For example, with dataset in (1.), count in df.groupby("favorite_subjects")["student"].describe() would be Math : 2, Stats : 1, Physics : 1

Question 8
3.

In [4]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
df.isna().sum()

NameError: name 'pd' is not defined

In [5]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanics.csv"
td = pd.read_csv(url)
td.isna().sum()

td.describe()

HTTPError: HTTP Error 404: Not Found

In [6]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
td = pd.read_csv(url)
td.isna().sum()

td.describe()
TD.groupby("age")["survived"].describe()

NameError: name 'TD' is not defined

In [7]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
td = pd.read_csv(url
td.isna().sum()

td.describe()
td.groupby("age")["survived"].describe()

SyntaxError: '(' was never closed (762864277.py, line 3)

In [8]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
td = pd.read_csv(url)
td.isna().sum()

td.describe()
td.groupby("age")["survived"].describle()

AttributeError: 'SeriesGroupBy' object has no attribute 'describle'

In [9]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
td = pd.read_csv(url)
td.isna().sum()

td.describe()
td.groupby("aGe")["survived"].describe()

KeyError: 'aGe'

In [10]:
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
td = pd.read_csv(url)
td.isna().sum()

td.describe()
td.groupby("age")[survived].describe()

NameError: name 'survived' is not defined